# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [21]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [4]:
#todo: 
numeros = np.arange(10)
print(numeros)


[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [8]:
#todo:
ceros = np.zeros(5, dtype = int)
ceros[2] = 5
print(ceros)

[0 0 5 0 0]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [15]:
#todo:
matriz = np.random.rand(3, 3)
matriz_redondeada = np.round(matriz, 2)
print(matriz_redondeada)

[[0.46 0.19 0.3 ]
 [0.36 0.32 0.85]
 [0.15 0.73 0.54]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [28]:
#todo:

arr = np.array([10, 20, 30, 40, 50])
arr = arr + 5

print(arr)

numero_aleatorio = np.random.randint(1, 10)
print(f"El numero aleatorio es: {numero_aleatorio}")

arr = arr * numero_aleatorio

print(arr)


[15 25 35 45 55]
El numero aleatorio es: 6
[ 90 150 210 270 330]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [29]:
#todo:
matriz_identidad = np.eye(4)
print(matriz_identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [60]:
#todo: 

arr_par = np.arange(0, 21, 2)
print(f"El array es : {arr_par}")

numero_aleatorio = np.random.randint(1, 10)
print(f"El numero aleatorio es: {numero_aleatorio}")

suma = arr_par + numero_aleatorio
print(f"Suma (array + el numero aleatorio): {suma}")

resta = arr_par - numero_aleatorio
print(f"Resta (array - numero aleatorio) {resta}")

multiplicacion = arr_par * numero_aleatorio
print(f"Multiplicacion (array * numero aleatorio) {multiplicacion}")

division = arr_par / numero_aleatorio
print(f"Division (array / numero aleatorio) {division}")




El array es : [ 0  2  4  6  8 10 12 14 16 18 20]
El numero aleatorio es: 8
Suma (array + el numero aleatorio): [ 8 10 12 14 16 18 20 22 24 26 28]
Resta (array - numero aleatorio) [-8 -6 -4 -2  0  2  4  6  8 10 12]
Multiplicacion (array * numero aleatorio) [  0  16  32  48  64  80  96 112 128 144 160]
Division (array / numero aleatorio) [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5 ]
